# Generated by Django 5.1.1 on 2025-02-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('CompanySize', models.CharField(choices=[('T', '1-10'), ('S', '10-100'), ('M', '100-1000'), ('L', '1000-10000'), ('XL', '10000-100000'), ('2XL', '100000+')], max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('image', models.ImageField(upload_to='PartnerImages')),
            ],
        ),
    ]
